# Generated by Django 4.2 on 2023-05-10 02:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish_list', '0002_dishresult_end_date_dishresult_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishresult',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 17, 2, 55, 2, 172093, tzinfo=datetime.timezone.utc)),
        ),
    ]
