# Generated by Django 4.2 on 2023-05-10 03:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish_list', '0003_alter_dishresult_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishresult',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 17, 3, 28, 52, 731153, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='DishList',
        ),
    ]
