# Generated by Django 4.2 on 2023-05-10 03:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish_list', '0004_alter_dishresult_end_date_delete_dishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishresult',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 17, 3, 54, 52, 759498, tzinfo=datetime.timezone.utc)),
        ),
    ]
