# Generated by Django 4.2 on 2023-05-11 08:43

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish_list', '0005_alter_dishresult_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishlistresult',
            name='dish_quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0)]),
        ),
        migrations.AlterField(
            model_name='dishresult',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 18, 8, 43, 13, 566207, tzinfo=datetime.timezone.utc)),
        ),
    ]
