# Generated by Django 4.2 on 2023-05-11 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish_list', '0006_alter_dishlistresult_dish_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishresult',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 18, 8, 50, 34, 287317, tzinfo=datetime.timezone.utc)),
        ),
    ]
