# Generated by Django 4.2 on 2023-05-20 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish_list', '0011_alter_dishresult_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishresult',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 27, 7, 32, 16, 913956, tzinfo=datetime.timezone.utc)),
        ),
    ]
