# Generated by Django 4.2 on 2023-05-08 15:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_itemingredients_procurement_validations_procurements'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemingredientroots',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='itemingredients',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='itemingredientroots',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemingredientroots',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
