# Generated by Django 4.2 on 2023-05-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0003_alter_itemingredientroots_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='group',
            field=models.CharField(choices=[('MEET', 'Viandes'), ('EPICE', 'Epices'), ('OTHERS', 'Autres'), ('COMPLEMENTS', 'Compléments'), ('CONSERVES', 'Conserves'), ('CEREAL', 'Céreals')], default='OTHERS', max_length=150),
        ),
    ]
