# Generated by Django 4.2 on 2023-05-11 08:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0001_initial'),
        ('dishes', '0007_itemingredients_spoil_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemingredients',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventories.inventories'),
        ),
        migrations.AddField(
            model_name='validations',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventories.inventories'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='unit_price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0)]),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit_price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0)]),
        ),
        migrations.AlterField(
            model_name='itemingredientroots',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0)]),
        ),
        migrations.AlterField(
            model_name='itemingredients',
            name='unit_price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0)]),
        ),
    ]
