# Generated by Django 4.2 on 2023-05-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0009_remove_itemingredientroots_dish_list_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemingredients',
            name='gap',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
