# Generated by Django 4.2 on 2023-05-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0010_itemingredients_gap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemingredients',
            name='gap',
        ),
        migrations.AddField(
            model_name='itemingredients',
            name='ingredient_stock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
