# Generated by Django 4.2 on 2023-04-27 22:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budgets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField(default=datetime.datetime(2023, 4, 27, 23, 22, 38, 608724))),
                ('end_date', models.DateTimeField(default=datetime.datetime(2023, 5, 4, 23, 22, 38, 608724))),
                ('statut', models.CharField(choices=[('CREATED', 'nouveau'), ('VALIDATED', 'validation'), ('ACQUISITION', 'acquisition'), ('CLOSED', 'closed'), ('REJECTED', 'rejeté')], default='created', max_length=150)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DishBudgets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dish_name', models.CharField(max_length=255)),
                ('dish_quantity', models.IntegerField()),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgets.budgets')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
