# Generated by Django 4.2 on 2023-05-21 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgets',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 28, 8, 22, 4, 234183, tzinfo=datetime.timezone.utc)),
        ),
    ]
