# Generated by Django 4.2 on 2023-04-27 22:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgets',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 4, 23, 22, 59, 183947)),
        ),
        migrations.AlterField(
            model_name='budgets',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 27, 23, 22, 59, 183947)),
        ),
        migrations.AlterField(
            model_name='budgets',
            name='statut',
            field=models.CharField(choices=[('CREATED', 'nouveau'), ('VALIDATED', 'validation'), ('ACQUISITION', 'acquisition'), ('CLOSED', 'closed'), ('REJECTED', 'rejeté')], default='CREATED', max_length=150),
        ),
    ]
