# Generated by Django 4.2 on 2023-04-27 22:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_alter_budgets_end_date_alter_budgets_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgets',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 4, 23, 32, 51, 414907)),
        ),
        migrations.AlterField(
            model_name='budgets',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 27, 23, 32, 51, 414907)),
        ),
    ]
