# Generated by Django 4.2 on 2023-05-23 07:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_alter_budgets_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgets',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 30, 7, 5, 19, 386091, tzinfo=datetime.timezone.utc)),
        ),
    ]
