# Generated by Django 4.2 on 2023-04-27 22:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0004_alter_budgets_end_date_alter_budgets_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemIngredientRoots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='budgets',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 4, 23, 54, 26, 686157)),
        ),
        migrations.AlterField(
            model_name='budgets',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 27, 23, 54, 26, 686157)),
        ),
        migrations.CreateModel(
            name='ItemIngredients',
            fields=[
                ('itemingredientroots_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='budgets.itemingredientroots')),
                ('unit_price', models.IntegerField()),
                ('dish_budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_ingredients', to='budgets.dishbudgets')),
            ],
            bases=('budgets.itemingredientroots',),
        ),
    ]
