# Generated by Django 4.2 on 2023-04-27 23:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0005_itemingredientroots_alter_budgets_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgets',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 5, 0, 11, 14, 559386)),
        ),
        migrations.AlterField(
            model_name='budgets',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 28, 0, 11, 14, 559386)),
        ),
        migrations.AlterField(
            model_name='itemingredients',
            name='dish_budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgets.dishbudgets'),
        ),
    ]
