# Generated by Django 4.2 on 2023-04-29 07:33

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0009_alter_budgets_end_date_alter_budgets_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemingredientroots',
            name='ingredient_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='budgets',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 6, 8, 31, 11, 444129)),
        ),
        migrations.AlterField(
            model_name='budgets',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 29, 8, 31, 11, 444129)),
        ),
    ]
