# Generated by Django 4.2 on 2023-04-29 07:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0010_itemingredientroots_ingredient_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgets',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 6, 8, 40, 40, 934183)),
        ),
        migrations.AlterField(
            model_name='budgets',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 29, 8, 40, 40, 934183)),
        ),
    ]
