# Generated by Django 4.2 on 2023-04-29 07:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0011_alter_budgets_end_date_alter_budgets_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgets',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 6, 7, 51, 2, 973133, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='budgets',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 29, 7, 51, 2, 973133, tzinfo=datetime.timezone.utc)),
        ),
    ]
