# Generated by Django 4.2 on 2023-04-29 08:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budgets', '0013_alter_budgets_end_date_alter_budgets_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgets',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 6, 8, 0, 54, 160001, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='budgets',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update_budget', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dishbudgets',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update_dish_budget', to=settings.AUTH_USER_MODEL),
        ),
    ]
