# Generated by Django 4.2 on 2023-04-29 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0014_alter_budgets_end_date_alter_budgets_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgets',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 6, 12, 19, 3, 383526, tzinfo=datetime.timezone.utc)),
        ),
    ]
