# Generated by Django 4.2 on 2023-05-01 21:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0016_alter_budgets_end_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgets',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='dishbudgets',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='budgets',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 8, 21, 22, 18, 890439, tzinfo=datetime.timezone.utc)),
        ),
    ]
