# Generated by Django 4.2 on 2023-05-02 05:50

import budgets.models
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import helpers.validator


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budgets', '0017_alter_budgets_options_alter_dishbudgets_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgets',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 9, 5, 50, 17, 571803, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=100, unique=True)),
                ('measure_unit', models.CharField(max_length=10)),
                ('unit_price', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=budgets.models.Ingredient.get_file_path, validators=[helpers.validator.validate_file_size, django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])])),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update_ingredient', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('unit_price', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=budgets.models.Dish.get_file_path, validators=[helpers.validator.validate_file_size, django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])])),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update_dish', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
