# Generated by Django 4.2 on 2023-05-06 12:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budgets', '0018_alter_budgets_end_date_ingredient_dish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgets',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 12, 34, 59, 753896, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='budgets',
            name='statut',
            field=models.CharField(choices=[('CREATED', 'nouveau'), ('VALIDATED', 'validation'), ('SUBMITTED', 'Soumis'), ('ACQUISITION', 'acquisition'), ('CLOSED', 'closed'), ('REJECTED', 'rejeté')], default='CREATED', max_length=150),
        ),
        migrations.CreateModel(
            name='Validations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField()),
                ('statut', models.BooleanField(default=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('budgets', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgets.budgets')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
