# Generated by Django 4.2 on 2023-05-06 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0019_alter_budgets_end_date_alter_budgets_statut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgets',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 12, 35, 44, 604929, tzinfo=datetime.timezone.utc)),
        ),
    ]
