# Generated by Django 4.2 on 2023-05-06 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0020_alter_budgets_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishbudgets',
            name='dish_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='budgets',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 12, 55, 50, 205132, tzinfo=datetime.timezone.utc)),
        ),
    ]
