# Generated by Django 4.2 on 2023-05-08 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '__first__'),
        ('procurement', '0002_testmodel125'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel125',
        ),
        migrations.AlterField(
            model_name='procurements',
            name='budget',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgets.budgets'),
        ),
        migrations.AlterField(
            model_name='procurements',
            name='statut',
            field=models.CharField(choices=[('CREATED', 'nouveau'), ('SUBMITTED', 'Soumis'), ('CLOSED', 'closed'), ('REJECTED', 'rejeté')], default='CREATED', max_length=150),
        ),
    ]
