# Generated by Django 4.2 on 2023-05-18 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dishes', '0010_itemingredients_gap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(default=0)),
                ('dish', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dishes.dish')),
                ('ingredient', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dishes.ingredient')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
