# Generated by Django 4.2 on 2023-05-11 08:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_spoil', '0004_sale_customer_first_name_sale_customer_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishlist',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='dishlist',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='dishlist',
            name='dish_quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0)]),
        ),
        migrations.AlterField(
            model_name='dishlist',
            name='unit_price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0)]),
        ),
    ]
